//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GOES_Application.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("e2SaerMjtPwaQ6541eTheWPbsed+cfGw0EfMYjopll1gGN0QLuJYJKHcPUCPChpmkA4NBgGzB1q9jK1BD" +
            "T/Oqu0Z+7PDZ27TM8+fPBc5c3S3wZfw030izA==")]
        public string MySQL {
            get {
                return ((string)(this["MySQL"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("goes@globalentryinterview.com")]
        public string MailFromAddress {
            get {
                return ((string)(this["MailFromAddress"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Goes Interview Tool")]
        public string MailFromName {
            get {
                return ((string)(this["MailFromName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Global Entry Interview Schedule Change")]
        public string MailSubject {
            get {
                return ((string)(this["MailSubject"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("box566.bluehost.com")]
        public string MailSMTPServer {
            get {
                return ((string)(this["MailSMTPServer"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("26")]
        public int MailPort {
            get {
                return ((int)(this["MailPort"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("goes@globalentryinterview.com")]
        public string MailUsername {
            get {
                return ((string)(this["MailUsername"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("LJNhO3sMjlreRX0+Y2fGow==")]
        public string MailPassword {
            get {
                return ((string)(this["MailPassword"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Setting {
            get {
                return ((string)(this["Setting"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public string FirstTime {
            get {
                return ((string)(this["FirstTime"]));
            }
            set {
                this["FirstTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string GoesUserName {
            get {
                return ((string)(this["GoesUserName"]));
            }
            set {
                this["GoesUserName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string GoesPassword {
            get {
                return ((string)(this["GoesPassword"]));
            }
            set {
                this["GoesPassword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string GoesLocation {
            get {
                return ((string)(this["GoesLocation"]));
            }
            set {
                this["GoesLocation"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<!DOCTYPE html>\r\n<html lang=\"en-US\">\r\n<head>\r\n    <meta charset=\"UTF-8\">\r\n    <me" +
            "ta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n    <link rel" +
            "=\"profile\" href=\"http://gmpg.org/xfn/11\">\r\n\r\n    <title>Interview Status &#8211;" +
            " Global Entry Interview Tool</title>\r\n    <link rel=\'stylesheet\' id=\'dashicons-c" +
            "ss\' href=\'https://www.globalentryinterview.com/wp-includes/css/dashicons.min.css" +
            "?ver=4.6.1\' type=\'text/css\' media=\'all\' />\r\n    <link rel=\'stylesheet\' id=\'sydne" +
            "y-bootstrap-css\' href=\'https://www.globalentryinterview.com/wp-content/themes/sy" +
            "dney/css/bootstrap/bootstrap.min.css?ver=1\' type=\'text/css\' media=\'all\' />\r\n    " +
            "<link rel=\'stylesheet\' id=\'sydney-body-fonts-css\' href=\'//fonts.googleapis.com/c" +
            "ss?family=Source+Sans+Pro%3A400%2C400italic%2C600&#038;ver=4.6.1\' type=\'text/css" +
            "\' media=\'all\' />\r\n    <link rel=\'stylesheet\' id=\'sydney-headings-fonts-css\' href" +
            "=\'//fonts.googleapis.com/css?family=Raleway%3A400%2C500%2C600&#038;ver=4.6.1\' ty" +
            "pe=\'text/css\' media=\'all\' />\r\n    <link rel=\'stylesheet\' id=\'sydney-style-css\' h" +
            "ref=\'https://www.globalentryinterview.com/wp-content/themes/sydney/style.css?ver" +
            "=4.6.1\' type=\'text/css\' media=\'all\' />\r\n    <style id=\'sydney-style-inline-css\' " +
            "type=\'text/css\'>\r\n        .site-title {\r\n            font-size: 32px;\r\n        }" +
            "\r\n\r\n        .site-description {\r\n            font-size: 16px;\r\n        }\r\n\r\n    " +
            "    #mainnav ul li a {\r\n            font-size: 14px;\r\n        }\r\n\r\n        h1 {\r" +
            "\n            font-size: 52px;\r\n        }\r\n\r\n        h2 {\r\n            font-size:" +
            " 42px;\r\n        }\r\n\r\n        h3 {\r\n            font-size: 32px;\r\n        }\r\n\r\n  " +
            "      h4 {\r\n            font-size: 25px;\r\n        }\r\n\r\n        h5 {\r\n           " +
            " font-size: 20px;\r\n        }\r\n\r\n        h6 {\r\n            font-size: 18px;\r\n    " +
            "    }\r\n\r\n        body {\r\n            font-size: 14px;\r\n        }\r\n\r\n        .hea" +
            "der-image {\r\n            background-size: cover;\r\n        }\r\n\r\n        .header-i" +
            "mage {\r\n            height: 200px;\r\n        }\r\n\r\n        .site-header.float-head" +
            "er {\r\n            background-color: rgba(0,0,0,0.9);\r\n        }\r\n\r\n        @medi" +
            "a only screen and (max-width: 991px) {\r\n            .site-header {\r\n            " +
            "    background-color: #000000;\r\n            }\r\n        }\r\n\r\n        .site-title " +
            "a, .site-title a:hover {\r\n            color: #ffffff;\r\n        }\r\n\r\n        .sit" +
            "e-description {\r\n            color: #ffffff;\r\n        }\r\n\r\n        #mainnav ul l" +
            "i a, #mainnav ul li::before {\r\n            color: #ffffff;\r\n        }\r\n\r\n       " +
            " #mainnav .sub-menu li a {\r\n            color: #ffffff;\r\n        }\r\n\r\n        #m" +
            "ainnav .sub-menu li a {\r\n            background: #1c1c1c;\r\n        }\r\n\r\n        " +
            ".text-slider .maintitle, .text-slider .subtitle {\r\n            color: #ffffff;\r\n" +
            "        }\r\n\r\n        body {\r\n            color: #767676;\r\n        }\r\n\r\n        #" +
            "secondary {\r\n            background-color: #ffffff;\r\n        }\r\n\r\n            #s" +
            "econdary, #secondary a, #secondary .widget-title {\r\n                color: #7676" +
            "76;\r\n            }\r\n\r\n        .footer-widgets {\r\n            background-color: #" +
            "252525;\r\n        }\r\n\r\n        .site-footer {\r\n            background-color: #1c1" +
            "c1c;\r\n        }\r\n\r\n            .site-footer, .site-footer a {\r\n                c" +
            "olor: #666666;\r\n            }\r\n\r\n        .overlay {\r\n            background-colo" +
            "r: #000000;\r\n        }\r\n\r\n        .page-wrap {\r\n            padding-top: 83px;\r\n" +
            "        }\r\n\r\n        .page-wrap {\r\n            padding-bottom: 100px;\r\n        }" +
            "\r\n    </style>\r\n\r\n    <style type=\"text/css\">\r\n        .header-image {\r\n        " +
            "  /*   background-image: url(https://www.globalentryinterview.com/goes/wp-conten" +
            "t/uploads/2016/08/cropped-20121224_102406-e1472222003286-2.jpg); */\r\n           " +
            " display: block;\r\n        }\r\n\r\n        @media only screen and (max-width: 1024px" +
            ") {\r\n            .header-inner {\r\n                display: block;\r\n            }" +
            "\r\n\r\n            .header-image {\r\n                background-image: none;\r\n      " +
            "          height: auto !important;\r\n            }\r\n        }\r\n    </style>\r\n</he" +
            "ad>\r\n\r\n<body class=\"page page-id-11 page-template-default logged-in no-customize" +
            "-support\">\r\n    <div id=\"page\" class=\"hfeed site\">\r\n                <div class=\"" +
            "container\">\r\n                    <div class=\"row\">\r\n                        <div" +
            " class=\"col-md-6 col-sm-8 col-xs-12\">\r\n                            <h3 class=\"si" +
            "te-title\"><a href=\"https://www.globalentryinterview.com\" rel=\"home\">Global Entry" +
            " Interview Tool</a></h3>\r\n                            <h3 class=\"site-descriptio" +
            "n\">Automated Global Entry Interview Scheduling</h3>\r\n                        </d" +
            "iv>\r\n                    </div>\r\n                </div>\r\n\r\n            </div>\r\n<" +
            "!-- #masthead -->")]
        public string MailHeader {
            get {
                return ((string)(this["MailHeader"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"        <a class=""go-top""><i class=""fa fa-angle-up""></i></a>

        <footer id=""colophon"" class=""site-footer"" role=""contentinfo"">
            <div class=""site-info container"">
                Copyright - 2016, Robert LeRoy
                <span class=""sep"">  </span>
                &nbsp;

            </div><!-- .site-info -->
        </footer><!-- #colophon -->
    </div><!-- #page -->

</body>
</html>")]
        public string MailFooter {
            get {
                return ((string)(this["MailFooter"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"        <div id=""content"" class=""page-wrap"">
            <div class=""container content-wrapper"">
                    <h3 class=""title-post"">Interview Schedule Change</h3>

                <h3>Success!</h3>

                <h6>
                    We found a new date for your global Entry Interview.  The new date is <strong style=""color: rgba(255,0,0,0.9);""> <==date==>


                    </strong>.
                </h6>
                <h6>You should login into the GOES website (<a href=""https://goes-app.cbp.dhs.gov/goes/jsp/login.jsp"">https://goes-app.cbp.dhs.gov/goes/jsp/login.jsp</a>) and confirm the date and location.</h6>
                <h6>You can, of course, reset the tool and continue to look for an earlier appointment at https://www.globalentryinterview.com/user-status.</h6>                <h6>Thanks for using our tool,<br />Bob</h6>            </div>        </div><!-- #content -->")]
        public string MailBodyHit {
            get {
                return ((string)(this["MailBodyHit"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"
        <div id=""content"" class=""page-wrap"">
            <div class=""container content-wrapper"">
                <h3 class=""title-post"">Global Entry Interview -- Error Processing your Interview</h3>


                <h6>
                    We started the process but encountered an error.  Your interview has not changed.
                </h6>
                <h6> The specific error message is:</h6>
                
<p style=""color:red"">

                 <==here==>

                </p>
                <h6>After you fix the error, you can reset the tool and continue to search for an earlier appointment at https://www.globalentryinterview.com/user-status.</h6>                <h6>Thanks for using our tool,<br />Bob</h6>            </div>        </div><!-- #content -->")]
        public string MailBodyError {
            get {
                return ((string)(this["MailBodyError"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"        <div id=""content"" class=""page-wrap"">
            <div class=""container content-wrapper"">
                 <h3>Global Entry Interview -- Support Issue</h3>
                
                <h6> The specific error message is:</h6>
                <p
>
                 <==here==>                     
                </p>
            </div>        </div><!-- #content -->")]
        public string MailBodySupport {
            get {
                return ((string)(this["MailBodySupport"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0720")]
        public string AppMode {
            get {
                return ((string)(this["AppMode"]));
            }
        }
    }
}
